ProjectBuilder.Web.MVC/Models/UserTreatmentsViewModel.cs
namespace ProjectBuilder.Web.MVC.Models
{
    public class UserTreatmentsViewModel
    {
        public int UserTreatmentsId { get; set; }
        public string UserTreatmentName { get; set; }
    }
}

ProjectBuilder.Web.MVC/Controllers/UserTreatmentsController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectBuilder.Core;
using ProjectBuilder.Core.Models;
using ProjectBuilder.Web.MVC.Models;

namespace ProjectBuilder.Web.MVC.Controllers
{
    public class UserTreatmentsController : Controller
    {
        private readonly IRepository<UserTreatmentTypeModel> _repository;
        public UserTreatmentsController(IRepository<UserTreatmentTypeModel> repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            if (User.Identity?.IsAuthenticated == true && HttpContext.Session.GetString("RoleName") != null)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> ApplyPagination(JqueryDatatableParam param)
        {
            var userTreatments = await _repository.GetAllAsync();
            var displayResult = userTreatments.Skip(param.iDisplayStart)
                .Take(param.iDisplayLength).ToList();
            var totalRecords = userTreatments.Count();
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            });
        }

        [HttpGet]
        public async Task<IActionResult> GetUserTreatment(int id)
        {
            var userTreatment = await _repository.FindAsync(id);
            var userTreatmentViewModel = new UserTreatmentsViewModel
            {
                UserTreatmentsId = userTreatment.UserTreatmentsId,
                UserTreatmentName = userTreatment.UserTreatmentName,
            };
            return Json(userTreatmentViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditUserTreatments(UserTreatmentsViewModel model)
        {
            if (string.IsNullOrEmpty(model.UserTreatmentName))
                return View("Error", new ErrorViewModel() { ErrorMessage = "the provided information are not valid to edit a User Treatments" });
            var pairs = new Dictionary<string, object>
            {
                { nameof(model.UserTreatmentName), model.UserTreatmentName }
            };
            await _repository.UpdateAsync(model.UserTreatmentsId, pairs);
            await _repository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> DeleteUserTreatments(UserTreatmentsViewModel model)
        {
            var role = await _repository.DeleteAsync(model.UserTreatmentsId);
            _repository.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

ProjectBuilder.Web.MVC/Views/UserTreatments/Index.cshtml
@model UserTreatmentsViewModel
@{
    ViewData["Title"] = "User Treatments";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />

<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>

<partial name="~/Views/Shared/navbarshared/_SetupsSidebar.cshtml" />
<div class="container-fluid" style="height:730px;margin-top:50px;overflow-y:auto;">



<div class="card">
    <div class="card-body">
            <h4>User Treatments</h4>

        <div class="row align-content-center  m-2">

            <div class="table-responsive">

                <table class="table table-bordered table-hover table-striped" id="userTreatmentsTable">
                    <thead class="bg-success text-white">
                        <tr>
                            <th>
                                UserTreatmentTypeNo
                            </th>
                            <th>
                                UserTreatmentName
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


</div>



@*Delete Modal*@
<div class="modal fade" id="deletealert" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="deletealertLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deletealertLabel">Delete User Treatments</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center">
                <i class="bi bi-exclamation-octagon-fill text-danger fa-2x me-3"></i>
                <span>
                    Are you sure you want to delete the selected User Treatments ?
                </span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form id="deleteform" asp-antiforgery="true" asp-action="DeleteUserTreatments" asp-controller="UserTreatments" method="post">
                    <input asp-for="UserTreatmentsId" id="userTreatmentsId" name="UserTreatmentsId" hidden />
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

@*Edit Modal*@

<div class="modal fade" id="EditUserTreatmentForm" tabindex="-1" role="dialog" aria-labelledby="EditUserTreatmentFormLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="EditParameterFormLabel">Edit User Treatments</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="editUserTreatment" class="needs-validation" asp-controller="UserTreatments" asp-action="EditUserTreatments" method="post">
                <div class="modal-body">
                    <input asp-for="UserTreatmentsId" id="userTreatmentsIdE" name="UserTreatmentsId" hidden />
                    <div class="mb-3">
                        <label for="UserTreatmentName" class="form-label">UserTreatmentName</label>
                        <input asp-for="UserTreatmentName" id="userTreatmentName" type="text" name="UserTreatmentName" class="form-control" required />
                        <div class="invalid-feedback">Field is required</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        $('#userTreatmentsTable').DataTable({
            "processing": true,
            "serverSide": true,
            "bSearchable": true,
            "order": [[1, 'asc']],
            "language": {
                "emptyTable": "No record found.",
                "processing":
                    '<i class="fa fa-spinner fa-spin fa-3x fa-fw" style="color:#2a2b2b;"></i><span class="sr-only">Loading...</span> '
            },
            "sAjaxSource": "/UserTreatments/ApplyPagination",
            "columns": [
                {
                    "data": "userTreatmentsId",
                    "autoWidth": true,
                    "searchable": true
                },
                {
                    "data": "userTreatmentName",
                    "autoWidth": true,
                    "searchable": true
                },
                {
                    "data": null,
                    title: "Actions",
                    orderable: false,
                    defaultContent: '',
                    render: function (data, type, row) {
                        var inner = `<button onclick="oneditingUserTreatment.bind(this)()" value="` + row.userTreatmentsId + `" class="btn btn-primary mb-1">
                        <i class="bi bi-pencil-square"></i>
                    </button>
                                        <button type="button" value="` + row.userTreatmentsId + `"onclick="onedeletingUserTreatment.bind(this)()" class="btn btn-danger mb-1" data-bs-toggle="modal" data-bs-target="#deletealert">
                        <i class="bi bi-trash"></i>
                    </button>`;
                        return inner;
                    }
                }
            ]
        });

    });

    function oneditingUserTreatment() {
        $.ajax(
            {
                type: 'Get',
                dataType: 'JSON',
                url: '/UserTreatments/GetUserTreatment',
                data: { id: this.value },
                success:
                    function (response) {
                        debugger;
                        var form = document.getElementById('editUserTreatment');
                        $('#userTreatmentName').val(response.userTreatmentName);
                        $('#userTreatmentsIdE').val(response.userTreatmentsId);
                        var model = document.getElementById('EditUserTreatmentForm');
                        var formModel = bootstrap.Modal.getOrCreateInstance(model);
                        formModel.show();
                    },
                error:
                    function (response) {

                    }
            });
    }

    function onedeletingUserTreatment() {
        $.ajax(
            {
                type: 'Get',
                dataType: 'JSON',
                url: '/UserTreatments/GetUserTreatment',
                data: { id: this.value },
                success:
                    function (response) {
                        debugger;
                        var form = document.getElementById('deleteform');
                        $('#userTreatmentsId').val(response.userTreatmentsId);
                    },
                error:
                    function (response) {

                    }
            });
    }

</script>