ProjectBuilder.Web.MVC/Controllers/Outputs/Charts/ChartsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectBuilder.Core;
using ProjectBuilder.DataAccess;
using ProjectBuilder.Web.MVC.Models;

namespace ProjectBuilder.Web.MVC.Controllers
{
    [Authorize]
    public class ChartsController : Controller
    {
        private readonly IRepository<ScenarioModel> _scenarios;
        private readonly IRepository<CountyModel> _counties;

        public ChartsController(IRepository<ScenarioModel> scenarios,IRepository<CountyModel> counties)
        {
           _scenarios = scenarios;
           _counties = counties;
        }
        public async Task<IActionResult> Needs(int? scenid)
        {
            var chartsViewModel = await LoadChartViewModel(scenid);
            return View("~/Views/Outputs/Charts/Needs.cshtml",chartsViewModel);
        }
        public async Task<IActionResult> PotentialBenefits(int? scenid)
        {
            var chartsViewModel = await LoadChartViewModel(scenid);
            return View("~/Views/Outputs/Charts/PotentialBenefits.cshtml",chartsViewModel);
        }
        public async Task<IActionResult> Budget(int? scenid)
        {
            var chartsViewModel = await LoadChartViewModel(scenid);
            return View("~/Views/Outputs/Charts/Budget.cshtml",chartsViewModel);
        }

        public async Task<IActionResult> BudgetSpent(int? scenid)
        {
            var chartsViewModel = await LoadChartViewModel(scenid);
            return View("~/Views/Outputs/Charts/BudgetSpent.cshtml",chartsViewModel);
        }

        private async Task<ChartsViewModel> LoadChartViewModel(int? scenid)
        {
            ChartsViewModel chartsViewModel = new();
            chartsViewModel.ScenarioId = scenid;
            if (scenid.HasValue)
            {
                var scenario = await _scenarios.FindAsync(scenid.Value);
                chartsViewModel.ScenarioName = scenario is null ? "" : scenario.ScenarioName;
            }
            var counties = await _counties.GetAllAsync();
            chartsViewModel.Districts = counties.Select(c => c.District).Distinct().OrderBy(d => d);
            return chartsViewModel;
        }
    }
}

ProjectBuilder.Web.MVC/Controllers/Outputs/Charts/ChartsDataController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectBuilder.Core;
using ProjectBuilder.Core.Repositories;

namespace ProjectBuilder.Web.MVC.Controllers
{
    [Authorize]
    public class ChartsDataController : Controller
    {
        private readonly IMapper _mapper;

        public ChartsDataController(IMapper mapper)
        {
            _mapper = mapper;
        }
        [HttpPost]
        public async Task<IActionResult> LoadNeedCharts(int? scenId, int? district, int? asset)
        {
            if (!scenId.HasValue && !district.HasValue)
                return BadRequest("You need to select a scenario and a district first");
            if (!scenId.HasValue)
                return BadRequest("You need to select a scenario");
            if (!district.HasValue)
                return BadRequest("You need to select a district");
            var needsUnit = HttpContext.RequestServices.GetRequiredService<IChartsNeedsUnitOfWork>();
            switch (asset)
            {
                case 0:
                    var bridgecharts = await LoadSelectedChart<BridgeNeedsModel>(scenId, district, needsUnit.BridgeNeedsRepo);
                    return Json(_mapper.Map<ChartsDataModel>(bridgecharts));
                case 1:
                    var pavementcharts = await LoadSelectedChart<PavementNeedsModel>(scenId, district, needsUnit.PavementNeedsRepo);
                    return Json(_mapper.Map<ChartsDataModel>(pavementcharts));
                default:
                    var allneeds = await LoadSelectedChart<AllNeedsModel>(scenId, district, needsUnit.AllNeedsRepo);
                    return Json(_mapper.Map<ChartsDataModel>(allneeds));
            }
        }
        [HttpPost]
        public async Task<IActionResult> LoadPotentialBenefitsCharts(int? scenId, int? district, int? asset)
        {
            if (!scenId.HasValue && !district.HasValue)
                return BadRequest("You need to select a scenario and a district first");
            if (!scenId.HasValue)
                return BadRequest("You need to select a scenario");
            if (!district.HasValue)
                return BadRequest("You need to select a district");
            var potentialBenefits = HttpContext.RequestServices.GetRequiredService<IChartsPotentialBenefitsUnitOfWork>();
            switch (asset)
            {
                case 0:
                    var bridgecharts = await LoadSelectedChart<BridgePotentialBenefitsModel>(scenId, district, potentialBenefits!.BridgePotentialBenefitsRepo);
                    return Json(_mapper.Map<ChartsDataModel>(bridgecharts));
                case 1:
                    var pavementcharts = await LoadSelectedChart<PavementPotentialBenefitsModel>(scenId, district, potentialBenefits!.PavementPotentialBenefitsRepo);
                    return Json(_mapper.Map<ChartsDataModel>(pavementcharts));
                default:
                    var allneeds = await LoadSelectedChart<AllPotentialBenefitsModel>(scenId, district, potentialBenefits!.AllPotentialBenefitsRepo);
                    return Json(_mapper.Map<ChartsDataModel>(allneeds));
            }
        }
        [HttpPost]
        public async Task<IActionResult> LoadBudgetCharts(int? scenId, int? district)
        {
            if (!scenId.HasValue && !district.HasValue)
                return BadRequest("You need to select a scenario and a district first");
            if (!scenId.HasValue)
                return BadRequest("You need to select a scenario");
            if (!district.HasValue)
                return BadRequest("You need to select a district");
            var budgetRepo = HttpContext.RequestServices.GetRequiredService<IRepository<BudgetModel>>();
            var result = await LoadSelectedChart(scenId, district, budgetRepo);
            if (result.Count <= 0)
                return Json(null);
            return Json(_mapper.Map<ChartsDataModel>(result));
        }
        [HttpPost]
        public async Task<IActionResult> LoadBudgetSpentCharts(int? scenId, int? district)
        {
            if (!scenId.HasValue && !district.HasValue)
                return BadRequest("You need to select a scenario and a district first");
            if (!scenId.HasValue)
                return BadRequest("You need to select a scenario");
            if (!district.HasValue)
                return BadRequest("You need to select a district");
            var budgetSpent = HttpContext.RequestServices.GetRequiredService<IRepository<BudgetSpentModel>>();
            var result = await LoadSelectedChart(scenId, district, budgetSpent);
            if (result.Count <= 0)
                return Json(null);
            return Json(_mapper.Map<ChartsDataModel>(result));
        }
        private async Task<List<T>> LoadSelectedChart<T>(int? scenId, int? district, IRepository<T> repository) where T : class
        {
            var filter = new Dictionary<string, object>()
            {
                { "ScenarioId", scenId },
                { "District", district }
            };
            repository.ApplyFilter(filter);
            var result = await repository.GetAllAsync();
            return result;
        }
    }
}

ProjectBuilder.Web.MVC/Controllers/Outputs/ProjectTreatmentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;
using ProjectBuilder.Core;
using ProjectBuilder.DataAccess;
using ProjectBuilder.Web.MVC.Models;
using System.Data.Entity;
using System.Runtime.CompilerServices;

namespace ProjectBuilder.Web.MVC.Controllers
{
    [Authorize]
    public class ProjectTreatmentsController : Controller
    {
        private readonly ITreatmentUnitOfWork _treatmentUnitOfWork;
        private readonly IProjectRepository _projects;
        private readonly IFilterUnitOfWork _filterUnitOfWork;
        private readonly IProjectTreatmentRepository _projectTreatment;
		private ProjectBuilderDbContext _context;

		public ProjectTreatmentsController(ITreatmentUnitOfWork treatmentUnitOfWork, IProjectTreatmentRepository projectTreatment, IProjectRepository project,IFilterUnitOfWork filterUnitOfWork, ProjectBuilderDbContext context)
        {
            _treatmentUnitOfWork = treatmentUnitOfWork;
            _filterUnitOfWork = filterUnitOfWork;
            _projects = project;
            _projectTreatment = projectTreatment;
            _context = context;
        }
        public async Task<IActionResult> Index(int? scenid,int? projectid)
        {
            var scenName = "";
            var projectTreatments = new ProjectTreatmentsViewModel();
            if(scenid.HasValue)
            {
                var scenario = await _filterUnitOfWork.ScenarioRepo.FindAsync(scenid.Value);
                scenName = scenario is null ? "" : scenario.ScenarioName;
                projectTreatments.Years = await _filterUnitOfWork.ProjectTreatmentRepo.GetYears(scenid.Value);
            }
            projectTreatments.ScenarioName = scenName;
            projectTreatments.ProjectId = projectid;
            projectTreatments.ScenarioId = scenid;
            TempData["ScenId"] = scenid;
            TempData["ProjectId"] = projectid;
            return View("~/Views/Outputs/ProjectTreatments.cshtml",projectTreatments);
        }

        [HttpPost]
        public IActionResult ApplyFilter(TreatmentSearchModel filter)
        {
            TempData["Filter"] = JsonConvert.SerializeObject(filter);
            return Ok();
        }
        public async Task<ActionResult> ApplyPagination(JqueryDatatableParam param)
        {
               var treatments = await LoadProjectTreatments();
               var search_val = (Request.Query["sSearch"]).ToString();
               var sort_col = (Request.Query["iSortCol_0"]);
               var sort_column = (Request.Query["mDataProp_" + sort_col]).ToString();
               var sortDirection = (Request.Query["sSortDir_0"]).ToString();
               var propertyInfo = typeof(ProjectTreatmentModel).GetProperties().FirstOrDefault(x => x.Name.ToLower().Equals(sort_column.ToLower()));
               if (search_val != "")
                    {
                        treatments = treatments.Where(
                            t => t.Section.ToLower().ToString().Contains(search_val.ToLower()) ||
                            (t.AssetType == "P" && "Pavement".ToLower().Contains(search_val.ToLower())) ||
                            (t.AssetType == "B" && "Bridge".ToLower().Contains(search_val.ToLower())) ||
                            t.District.ToString().Contains(search_val.ToLower()) ||
                            t.County.ToLower().ToString().Contains(search_val.ToLower()) ||
                            t.TreatmentType.ToLower().ToString().Contains(search_val.ToLower()) ||
                            t.BridgeId.ToString().Contains(search_val.ToLower()) ||
                            t.Route.ToString().Contains(search_val.ToLower()) ||
                            t.Interstate.ToString().Contains(search_val.ToLower()) ||
                            t.Direction.ToString().Contains(search_val.ToLower()) ||
                            Math.Round((decimal)t.TotalCost / 1000000, 2).ToString().Contains(search_val.ToLower()) ||
                            Math.Round((decimal)t.Benefit / 1000000, 2).ToString().Contains(search_val.ToLower()) ||
                            Math.Round((decimal)t.Risk, 2).ToString().Contains(search_val.ToLower()) ||
                            t.PreferredYear.ToString().Contains(search_val.ToLower()) ||
                            t.MinYear.ToString().Contains(search_val.ToLower()) ||
                            t.MaxYear.ToString().Contains(search_val.ToLower()) ||  
                            t.IndirectCostDesign.ToString().Contains(search_val.ToLower()) ||
                            t.IndirectCostRow.ToString().Contains(search_val.ToLower()) ||
                            t.IndirectCostUtilities.ToString().Contains(search_val.ToLower()) ||
                            t.IndirectCostOther.ToString().Contains(search_val.ToLower())
                            ).ToList();
                    }
                    treatments = sortDirection == "asc" && propertyInfo != default
                        ? treatments.OrderBy(t => propertyInfo.GetValue(t, null))
                        : treatments.OrderByDescending(t => propertyInfo.GetValue(t, null));
                    var displayResult = treatments.Skip(param.iDisplayStart).Take(param.iDisplayLength);
                    var totalRecords = treatments.Count();
                    return Json(new
                    {
                        param.sEcho,
                        iTotalRecords = totalRecords,
                        iTotalDisplayRecords = totalRecords,
                        aaData = displayResult
                    });
        }
        private async Task<IEnumerable<ProjectTreatmentModel>> LoadProjectTreatments()
        {
            var hasscenid = int.TryParse(TempData.Peek("ScenId")?.ToString(),out int scenid);
            var hasprojectid = int.TryParse(TempData.Peek("ProjectId")?.ToString(), out int projectid);
            if(!hasscenid || !hasprojectid)
                return Enumerable.Empty<ProjectTreatmentModel>();
            var filterdata = TempData.Peek("Filter");
            var filter = filterdata == null ? new() : JsonConvert.DeserializeObject<TreatmentSearchModel>(filterdata.ToString());
            filter.ScenarioId = scenid;
            filter.ProjectId = projectid;
           return await _filterUnitOfWork.ProjectTreatmentRepo.FilterProjectTreatments(filter);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteProjectTreatment(long? treatmentid, TreatmentViewModel treatmentViewModel)
        {
            var success = await _filterUnitOfWork.ProjectTreatmentRepo.DeleteAsync(treatmentid);
            await _filterUnitOfWork.SaveChangesAsync();
            if (success)
            {
                var scenario = await _context.Scenarios.FindAsync(treatmentViewModel.ScenarioId);

                if (scenario != null)
                {
                    scenario.Stale = true;
                    scenario.Notes = "Scenario Needs to be Run Again";
                    _context.Scenarios.Update(scenario);
                    _context.SaveChanges();
                }

            }
            if (!success)
            {
                return BadRequest("Could not delete the selected Project Treatment because it was not found.");
            }

            return Ok($"Treatment with id: {treatmentid} has been successfully deleted");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProjectTreatment(TreatmentViewModel treatmentViewModel)
        {
            ValidateTreatmentOnEditing(treatmentViewModel);
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
                return BadRequest(Json(errors));
            }

            var success = await _filterUnitOfWork.ProjectTreatmentRepo.EditProjectTreatments(new ProjectTreatmentModel
            {
                ProjectTreatmentId = treatmentViewModel.ProjectTreatmentId,
                Benefit = treatmentViewModel.Benefit,
                DirectCost = treatmentViewModel.Cost,
                IsCommitted = treatmentViewModel.IsCommitted,
                UserTreatmentTypeNo = treatmentViewModel.TreatmentType,
                Risk = treatmentViewModel.Risk,
                PreferredYear = treatmentViewModel.PreferredYear,
                PriorityOrder = treatmentViewModel.PriorityOrder,
                MaxYear = treatmentViewModel.MaxYear,
                MinYear = treatmentViewModel.MinYear,
                IndirectCostDesign = treatmentViewModel.IndirectCostDesign,
                IndirectCostRow = treatmentViewModel.IndirectCostRow,
                IsUserCreated = true,
                IndirectCostOther = treatmentViewModel.IndirectCostOthers,
                IndirectCostUtilities = treatmentViewModel.IndirectCostUtilities
            });
			//var stale = await _filterUnitOfWork.ProjectTreatmentRepo.CheckStale(treatmentViewModel.ScenarioId);

			//if (!stale)
			//{
			//	var scenario = await _filterUnitOfWork.ScenarioRepo.FindAsync(treatmentViewModel.ScenarioId);
			//	scenario.Notes = "Scenario Needs to be Run Again";
			//	scenario.Stale = true;
			//	await _filterUnitOfWork.ScenarioRepo.UpdateAsync(scenario);
			//}
			//return Ok("Treatment was updated successfully.");
			//if (success)
			//{
			//    var scenario = await _filterUnitOfWork.ScenarioRepo.FindAsync(treatmentViewModel.ScenarioId);
			//    scenario.Notes = "Scenario Needs to be Run Again";
			//    await _filterUnitOfWork.ScenarioRepo.UpdateAsync(scenario);
			//}

			//if (!success)
			//    return BadRequest(Json("Could not upadate the selected treatment please try again."));
			//return Ok("Treatment was updated successfully.");
			if (success)
			{
				var scenario = await _context.Scenarios.FindAsync(treatmentViewModel.ScenarioId);

ProjectBuilder.Web.MVC/Views/Outputs/Charts/Budget.cshtml
@using ProjectBuilder.Web.MVC.Models;

@model ChartsViewModel

@{
    ViewData["Title"] = "Budget";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="charts_main-container">
    <partial name="~/Views/shared/navbarshared/_outputsnavbar.cshtml" />
    <div class="charts_maincontent">
        <div class="charts_main-header">
            <h1>Budget</h1>
            <h1>@Model.ScenarioName</h1>
        </div>
        <div class="charts_main-body">
            <div class="charts_main-filter">
                <div class="card">
                    <form asp-controller="ChartsData" asp-action="LoadBudgetCharts" class="charts_main-filter_form"
                          id="filterform" method="post" chart="budget">
                        <div class="charts_main-filter_form-body">
                            <input name="scenid" id="scenid" value="@Model.ScenarioId" hidden>

                            <select class="form-select" name="scenario_id" id="scenario_id" data-filter=" scenario">
                                <option value="" selected>Select Scenario</option>
                            </select>


                            <select class="form-select" name="district">
                                <option selected disabled>Select District</option>
                                @foreach (var district in Model.Districts)
                                {
                                    <option value="@district">District @district</option>
                                }
                            </select>
                        </div>
                        <button id="filter" type="submit" class="btn btn-primary">Filter</button>
                    </form>
                </div>
            </div>
            <div id="chartcontainer" class="charts_main-chart">
                @if (!Model.ScenarioId.HasValue)
                {
                    <div class="error_container">
                        <p>To view Budget Charts you need to select a scenario first.</p>
                    </div>
                }
                else
                {
                    <div class="error_container">
                        <p>To view Charts select a district first.</p>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Styles{
    <link rel="stylesheet" href="~/css/charts_styles.css" />
}

<div id="loader-container">
    <div id="loader" class="loader"></div>
</div>
    <script>
    function showLoader() {
        document.getElementById('loader-container').style.display = 'block';
    }

    function hideLoader() {
        document.getElementById('loader-container').style.display = 'none';
    }


    $(function () {
        var scenId = $('#scenid').val();


        $.ajax({
            type: 'GET',
            url: "/Scenarios/GetScenarios",
            contentType: 'application/json',
            success: function (response) {
                $("#scenario_id").html("<option value=''>Select Scenario</option>");
                $.each(response.scenarios, function (key, value) {
                    if (scenId == value.scenarioId)
                        $("#scenario_id").append("<option value='" + value.scenarioId + "' selected>" + value.scenarioName + "</option>");
                    else
                        $("#scenario_id").append("<option value='" + value.scenarioId + "'>" + value.scenarioName + "</option>");
                });
                hideLoader();
            }
        });


        showLoader();

        // Set a timeout to hide the loader after 3 seconds
        setTimeout(function () {
            hideLoader();
        }, 3000);


        $(document).on("change", "#scenario_id", function () {
            if ($(this).val())
                window.location.href = "/Charts/Budget?scenid=" + $(this).val();
            else
                window.location.href = "/Charts/Budget";
        });

        var currentUrl = window.location.href;
        var url = new URL(currentUrl);
        var searchParams = new URLSearchParams(url.search);
        var fromScenario = searchParams.get("fromscenario");
        if (fromScenario == "true") {
            $("#scenario_id").hide();
        }
    });

         function validateDropdown() {
            var scenariodropdown = document.getElementById('scenarioDropdown');
            var districtDropdown = document.getElementById('districtDropdown');

            var validationMessage = document.getElementById('validationMessage');

            if (scenariodropdown.value === "") {
                scenerioValidationMessage.textContent = 'Please select a scenario';
                return false;
            }
            else {
                scenerioValidationMessage.textContent = '';
            }

            if (districtDropdown.value === "") {
                districtValidationMessage.textContent = 'Please select a District';
                return false;
            }
            else {
                scenerioValidationMessage.textContent = '';
            }

            validationMessage.textContent = '';
            return true;
        }
</script>

ProjectBuilder.Web.MVC/Views/Outputs/Charts/BudgetSpent.cshtml
@using ProjectBuilder.Web.MVC.Models;

@model ChartsViewModel

@{
    ViewData["Title"] = "Budget Spent";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="charts_main-container">
    <partial name="~/Views/shared/navbarshared/_outputsnavbar.cshtml" />
    <div class="charts_maincontent">
        <div class="charts_main-header">
            <h1>Budget Spent</h1>
            <h1>@Model.ScenarioName</h1>
        </div>
        <div class="charts_main-body">
            <div class="charts_main-filter">
                <div class="card">
                    <form asp-controller="ChartsData" asp-action="LoadBudgetSpentCharts" class="charts_main-filter_form"
                          id="filterform" method="post" chart="budget">
                        <div class="charts_main-filter_form-body">
                            <input name="scenid" id="scenid" value="@Model.ScenarioId" hidden>

                            <select class="form-select" name="scenario_id" id="scenario_id" data-filter=" scenario">
                                <option value="" selected>Select Scenario</option>
                            </select>

                            <select class="form-select" name="district">
                                <option selected disabled>Select District</option>
                                @foreach (var district in Model.Districts)
                                {
                                    <option value="@district">District @district</option>
                                }
                            </select>
                        </div>
                        <button id="filter" type="submit" class="btn btn-primary">Filter</button>
                    </form>
                </div>
            </div>
            <div id="chartcontainer" class="charts_main-chart">
                @if (!Model.ScenarioId.HasValue)
                {
                    <div class="error_container">
                        <p>To view Budget Spent Charts you need to select a scenario first.</p>
                    </div>
                }
                else
                {
                    <div class="error_container">
                        <p>To view Charts select a district first.</p>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Styles{
    <link rel="stylesheet" href="~/css/charts_styles.css" />
}
<div id="loader-container">
    <div id="loader" class="loader"></div>
</div>
    <script>
    function showLoader() {
        document.getElementById('loader-container').style.display = 'block';
    }

    function hideLoader() {
        document.getElementById('loader-container').style.display = 'none';
    }


    $(function () {
        var scenId = $('#scenid').val();


        $.ajax({
            type: 'GET',
            url: "/Scenarios/GetScenarios",
            contentType: 'application/json',
            success: function (response) {
                $("#scenario_id").html("<option value=''>Select Scenario</option>");
                $.each(response.scenarios, function (key, value) {
                    if (scenId == value.scenarioId)
                        $("#scenario_id").append("<option value='" + value.scenarioId + "' selected>" + value.scenarioName + "</option>");
                    else
                        $("#scenario_id").append("<option value='" + value.scenarioId + "'>" + value.scenarioName + "</option>");
                });
                hideLoader();
            }
        });


        showLoader();

        // Set a timeout to hide the loader after 3 seconds
        setTimeout(function () {
            hideLoader();
        }, 3000);


        $(document).on("change", "#scenario_id", function () {
            if ($(this).val())
                window.location.href = "/Charts/BudgetSpent?scenid=" + $(this).val();
            else
                window.location.href = "/Charts/BudgetSpent";
        });

        var currentUrl = window.location.href;
        var url = new URL(currentUrl);
        var searchParams = new URLSearchParams(url.search);
        var fromScenario = searchParams.get("fromscenario");
        if (fromScenario == "true") {
            $("#scenario_id").hide();
        }
    });
        function validateDropdown() {
            var scenariodropdown = document.getElementById('scenarioDropdown');
            var districtDropdown = document.getElementById('districtDropdown');

            var validationMessage = document.getElementById('validationMessage');

            if (scenariodropdown.value === "") {
                scenerioValidationMessage.textContent = 'Please select a scenario';
                return false;
            }
            else {
                scenerioValidationMessage.textContent = '';
            }

            if (districtDropdown.value === "") {
                districtValidationMessage.textContent = 'Please select a District';
                return false;
            }
            else {
                scenerioValidationMessage.textContent = '';
            }

            validationMessage.textContent = '';
            return true;
        }
    </script>